### ISSUE TITLE
Results depend on lexical order of fallback implementations

### ISSUE THREAD

**Issue by cmb69** [llaville/php-compat-info#155]
Consider the following code:

    function do_something()
    {
        json_encode('foo');
    }
    
    if (!function_exists('json_encode')) {
        function json_encode() {
            // ...
        }
    }
    do_something();

The namespaces min is reported as 5.2.0, but if I put the the definition of do_something() at the end, the namespaces min is reported as 4.0.0. All other requirements are reported as 4.0.0 min.

**Comment by llaville** [comment]
I've reopened this issue, because the fix is not correct. Let me explains !

With such code as described in comment https://github.com/llaville/php-compat-info/issues/155#issue-52485910, the minimum PHP version and global namespace should be set to 4.0.0 and not 5.2.0 (as current).
This code is valid with older versions than 5.2, because the `json_encode()` function is declared

To be honest, the conditional code detection is a major challenge that I try actually to fix with the new API 4.0

**Comment by llaville** [comment]
The challenge to handle conditional code was also fixed. See #160
