### ISSUE TITLE
Total requirements do not include Constants

### ISSUE THREAD

**Issue by cmb69** [llaville/php-compat-info#158]
There seems to be a regression in 3.7.2 (works fine with 3.7.1), so that the Total doesn't include the Constants.

Test script:

    <?php
    
    echo PHP_EOL;
    mb_strtolower($text);

Output:

    Data Source Analysed
    
    Directories                                          1
    Files                                                1
    
    Global Analysis
    
                        Count Cond PHP min Elements highlight
     Extensions         2     0    4.3.10  Core
     Namespaces         1     0    4.3.0   +global
     Interfaces         0     0
     Traits             0     0
     Classes            0     0
     User Functions     0     0
     Internal Functions 1     0    4.3.0   mb_strtolower
     Constants          1     0    4.3.10  PHP_EOL
     Total                         4.3.0

**Comment by llaville** [comment]
I finally found origin of regression due to commit https://github.com/llaville/php-compat-info/commit/dbda65a7955bb04673d659d41ae02da409b3ef8c#diff-9e696e6927eb42cc9053c00ab419b201

The control on lines 681 - 683 is at wrong location and is in conflict with `visitConstantModel` that can't do its job

**Comment by llaville** [comment]
As new API 4.0 is not impacted by this issue, I'll attach to milestone 3.7.3 (no due date).
