### ISSUE TITLE
Reflection Class

### ISSUE THREAD

**Issue by benjaminfunk** [llaville/php-compat-info#162]
php-compact-info did not match

http://php.net/manual/de/reflectionclass.newinstancewithoutconstructor.php

as >=5.4.0

**Comment by llaville** [comment]
Please specify what php-compatinfo version you used !

**Comment by benjaminfunk** [comment]
Oh sorry. Its 3.7.2 as phar.

**Comment by llaville** [comment]
I'm sad to tell you that I cannot fixed it like a simple bug issue. Let me try to explain how it works.

This issue is also TRUE for the new API 4 (currently under development - latest version pretty stable is 4.0.0-alpha3).

CompatInfo 3 or 4 checks if it can find elements in it's dictionnary (one PHP file by extension in v3, and a SQLite database in v4).
Actually, only three extensions are fully documented (aqmp, haru, pthreads) https://github.com/llaville/php-compat-info/blob/master/tests/Reference/GenericTest.php#L55

And the stub https://github.com/llaville/php-compat-info/blob/master/tests/Reference/GenericTest.php#L442-L447 prevent to checks other extension to look up class methods available in each extension.

That's means in summary that I should add all other class methods for each extension supported in the dictionnary. A huge work that I will do but little step after little step.

Hope you understand. And as the branch 3 is features closed, I'll do this job only for v4 now !

**Comment by llaville** [comment]
This conclude the fix for CompatInfo 4.0
No backport will be provided, because too much info work. 

Thanks for reporting !
