### ISSUE TITLE
Missing extension on class inheritance

### ISSUE THREAD

**Issue by remicollet** [llaville/php-compat-info#171]
Tested with 4.0.0-rc2 against phpMyAdmin  4.4.0-rc1

IN Classes Analysis

      XMLWriter                             2       xmlwriter 5.1.2       5.1.2                   

In Extensions Analysis, xmlwriter is missing.

**Comment by llaville** [comment]
This issue came when a class inherit from another one that is part of an extension. 

In phpMyAdmin 4.4.0-rc1 code source, its comes two times : 

- phpMyAdmin-4.4.0-rc1-all-languages\libraries\plugins\schema\dia\Dia_Relation_Schema.class.php
  class PMA_DIA extends XMLWriter
- phpMyAdmin-4.4.0-rc1-all-languages\libraries\plugins\schema\svg\Svg_Relation_Schema.class.php
  class PMA_SVG extends XMLWriter 

NOTE: due to big file phpMyAdmin-4.4.0-rc1-all-languages\libraries\tcpdf\tcpdf.php, you can't analyse with a standard PHP distrib ( memory_limit = 128 )

TIP: invoke phpcompatinfo with `-d memory_limit=256M`

**Comment by llaville** [comment]
This is also affect when a class implements an interface that is part of an extension.
