### ISSUE TITLE
Config option "exclude" is not recognized

### ISSUE THREAD

**Issue by cmb69** [llaville/php-compat-info#188]
Apparently, the configuration option "source-providers" -> "exclude" is not recognized. I've tried `phpcompatinfo analyser:run .` with the following phpcompatinfo.json:

    {
        "source-providers": [
            {
                "in": ". as current",
                "name": "/\\.(php|inc|phtml)$/",
                "exclude": "vendor"
            }
        ],
        "plugins": [
        ],
        "analysers": [
        ],
        "services": [
        ]
    }

However, the files in the vendor/ directory are analysed. I've verified that this phpcompatinfo.json is actually used by inserting invalid JSON and checking with `phpcompatinfo config:validate`.

**Comment by llaville** [comment]
This is not a bug. Perharps I did not explained the major difference beetween API 4.0 and 3.x, but the `phpcompatinfo.json` config file is not necessary.  Especially when you parse single file or directory.

The config file, is used only for advanced developers, that want either : 

- to include a plugin (log, cache, notifier, ...)
- to config the symfony/finder 

But, BE CAREFULL, when you do this, you MUST USE the alias defined in config file

That means, when you don't use alias, and you specify something that look like a directory that exists (in your case `.` is always the current dir, and it always exists), entry in your `phpcompatinfo.json` is not used.
And for your the exclude option is not in effect.

Use instead this command line 

    phpcompatinfo analyser:run --alias current 

Rather than 

    phpcompatinfo analyser:run .

**Comment by cmb69** [comment]
Ah, now I understand, Thanks for the explanation.

And thanks for the good work. 4.0.0 looks great. :smile:

**Comment by llaville** [comment]
Thanks for yor feedback, and glad you enjoy the new version !
