### ISSUE TITLE
PDO Exception when missing php5-sqlite on debian

### ISSUE THREAD

**Issue by verfriemelt-dot-org** [llaville/php-compat-info#203]
# ./phpcompatinfo-4.3.0.phar

    [PDOException]
    could not find driver
 
    list [--xml] [--raw] [--format FORMAT] [--] [<namespace>]

that is all you get, when you do not have sqlite support installed, no hint whats missing what so ever.
i suggest you should add an exception handler for this and print a notice, that sqlite is required to use this tool

**Comment by llaville** [comment]
I'm very surprised that you may be able to install php-compatinfo 4.3 on your platform without pdo_sqlite extension, due to restriction : 

* for composer installation, it's https://github.com/llaville/php-compat-info/blob/master/composer.json#L24
* for fedora, it's https://github.com/remicollet/remirepo/blob/3fe8925a3ebc57c1a6f89fec4d816522542a60f0/php/bartlett/php-bartlett-PHP-CompatInfo/php-bartlett-PHP-CompatInfo.spec#L57

Composer in action, will give something like 
```
Using version ^4.3 for bartlett/php-compatinfo
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for bartlett/php-compatinfo ^4.3 -> satisfiable by bartlett/php-compatinfo[4.3.0].
    - bartlett/php-compatinfo 4.3.0 requires ext-pdo_sqlite * -> the requested PHP extension pdo_sqlite is missing from
your system.


Installation failed, reverting ./composer.json to its original content.
```
Fedora should have the same validation process (I can't give any example here: no VM available).
Perharps an expert can help you @remicollet  

The auto-diagnose did not yet check for pdo_sqlite, for technical architecture.
I could probably do something in phpcompatinfo itself.

**Comment by remicollet** [comment]
composer of distro package ensure that needed dependencies are available.
but nothing in the .phar mode.

**Comment by verfriemelt-dot-org** [comment]
indeed,
i found that tool via this page: http://php5.laurent-laville.org/compatinfo/manual/current/en/getting-started.html

and theres nothing stated , that i need sqlite support.
was a bit thumbling around, because i dont use sliqte on my devbox at all and started to google the code, checked the code and found the sqlite usage...

     apt-get install php5-sqlite

and now its working. but it should be mentioned on the getting started page ;)

**Comment by llaville** [comment]
You're right @remicollet , this is why I said 

> The auto-diagnose did not yet check for pdo_sqlite, for technical architecture.
I could probably do something in phpcompatinfo itself.

**Comment by llaville** [comment]
@verfriemelt-dot-org It's later on user doc http://php5.laurent-laville.org/compatinfo/manual/current/en/user-guide--installation.html

**Comment by verfriemelt-dot-org** [comment]
if youre using composer. since i was using the phar i just read again "grab it and youre good to go!" ;)

**Comment by remicollet** [comment]
> CompatInfo requires the json, libxml, pdo, pcre, and spl extensions. These extensions are usually compiled and enabled by default.

I don't see any mention about the pdo_sqlite driver ;)

**Comment by llaville** [comment]
Whatever solution I'll applied to enforce check requirements, did you mention your issue was with Debian ?

**Comment by verfriemelt-dot-org** [comment]
yea, debian 8

**Comment by llaville** [comment]
@verfriemelt-dot-org I've not understood that you used the phar version on Debian.
